Improve read and write functions
pyMBE-dev/pyMBE pull request #30
Opened 2024-04-08 14:19 UTC by paobtorres

2024-04-08 16:30 UTC, pm-blanco requested changes
@paobtorres thank you for taking care of this. Could you please update the main branch of your forked repository and then merge it to this branch and fix the merge conflicts?

I also checked the CI of the last commit on your branch and it is failing with your current implementation:
```bash
python3 testsuite/peptide_tests.py
fv-az568-256:pid5411: PSM3 can't open nic unit: 1 (err=23)
fv-az568-256:pid5411: PSM3 can't open nic unit: 1 (err=23)
fv-az568-256:pid5411: PSM3 can't open nic unit: 1 (err=23)
fv-az568-256:pid5411: PSM3 can't open nic unit: 1 (err=23)
Traceback (most recent call last):
  File "/home/runner/work/pyMBE/pyMBE/samples/Beyer2024/peptide.py", line 143, in <module>
    c_salt_calculated = pmb.create_added_salt(espresso_system=espresso_system,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/pyMBE/pyMBE/pyMBE.py", line 654, in create_added_salt
    self.create_particle(espresso_system=espresso_system, name=cation_name, number_of_particles=N_cation)
  File "/home/runner/work/pyMBE/pyMBE/pyMBE.py", line 819, in create_particle
    self.copy_df_entry(name=name,column_name='particle_id',number_of_copies=number_of_particles)
  File "/home/runner/work/pyMBE/pyMBE/pyMBE.py", line 607, in copy_df_entry
    df_by_name_repeated = self.pd.concat ([df_by_name]*(number_of_copies-1), ignore_index=True)
                                          ~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~
TypeError: can't multiply sequence by non-int of type 'numpy.float64'
Traceback (most recent call last):
Running tests for KKKKKDDDDD
  File "/home/runner/work/pyMBE/pyMBE/testsuite/peptide_tests.py", line 62, in <module>
    run_peptide_test(script_path=script_path,
  File "/home/runner/work/pyMBE/pyMBE/testsuite/peptide_tests.py", line 30, in run_peptide_test
    subprocess.check_output(run_command)
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/subprocess.py", line 466, in check_output
pH = 3
python3 /home/runner/work/pyMBE/pyMBE/samples/Beyer2024/peptide.py --sequence KKKKKDDDDD --pH 3 --mode test --no_verbose --output /tmp/tmpiloz45iy
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '/home/runner/work/pyMBE/pyMBE/samples/Beyer2024/peptide.py', '--sequence', 'KKKKKDDDDD', '--pH', '3', '--mode', 'test', '--no_verbose', '--output', '/tmp/tmpiloz45iy']' returned non-zero exit status 1.
make: *** [Makefile:12: tests] Error 1
```
could you please fix this?

2024-04-08 16:40 UTC, paobtorres commented
@pm-blanco Yes, I'm currently working on it .

2024-04-08 16:48 UTC, pm-blanco commented
@paobtorres ok, otherwise your implementation looks reasonable to me.

2024-04-09 12:31 UTC, paobtorres commented
@pm-blanco Finally solved all the merge problems. Now is ready for review

2024-04-10 16:43 UTC, paobtorres commented
@pm-blanco Ready for review! I adapted functions and scripts to consider parameter_of_the_potential a dict not a str.

2024-04-10 17:05 UTC, pm-blanco commented on pyMBE.py
> +        #     used_bond_df = used_bond_df.drop_duplicates(keep='first')
can you please remove this comments from the code?

2024-04-10 17:33 UTC, merged