Fix initial pos mol
pyMBE-dev/pyMBE pull request #34
Opened 2024-04-16 14:29 UTC by mariusaarsten

Fixing create_molecule when specific positions are provided.

2024-04-16 15:31 UTC, pm-blanco requested changes

2024-04-16 15:31 UTC, pm-blanco commented on pyMBE.py
> +                            if len(list_of_first_residue_positions) != number_of_molecules:
This sanity test should be moved to the begging of the function (there is no need to check for each loop iteration)

2024-04-16 15:31 UTC, pm-blanco commented on testsuite/create_molecule_position.py
> +import numpy as np
note that you have added two tests that do the same (or very similar) `testsuite/create_molecule_position.py` and `testsuite/create_molecule_position_test.py` please either remove one of them or if they do something different merge them into one

2024-04-18 14:07 UTC, pm-blanco commented
@mariusaarsten note that you need to change the name of the test in the `Makefile`, otherwise the CI crashes simply because it does not find the right file

2024-04-18 15:16 UTC, mariusaarsten commented
@pm-blanco Done! I think the pull request should be good now

2024-04-18 16:08 UTC, pm-blanco approved these changes
@mariusaarsten it looks good to me now, thank you for your work!

2024-04-18 16:08 UTC, merged