Update README.md with information about preprint
pyMBE-dev/pyMBE pull request #51
Opened 2024-05-04 17:28 UTC by davidbbeyer

Addresses #49 

@pm-blanco I have added a short note about the preprint and how to cite it to the Readme. My suggestion would be to merge this, but leave the issue open as a reminder (e.g. to replace the preprint by the paper eventually).

2024-05-04 18:00 UTC, pm-blanco requested changes
I agree with merging this PR now. I would leave the issue open not only as a reminder to update this info once we publish the article, but also to address the cite feature proposed in #5

2024-05-05 09:00 UTC, davidbbeyer commented on README.md
> +If you use pyMBE in your research, make sure to cite the preprint:
done

2024-05-05 09:00 UTC, davidbbeyer commented on README.md
> +Also make sure to properly cite the corresponding papers if you use the $\mathrm{p}K_{\mathrm{A}}$-sets or interaction parameters provided in the `parameters/` folder.
done

2024-05-05 11:24 UTC, pm-blanco approved these changes
Looks good to me

2024-05-05 11:24 UTC, merged