analysis tests
pyMBE-dev/pyMBE pull request #62
Opened 2024-05-17 16:24 UTC by kosovan

* [ ] `lib.analysis.block_analyze()`
* [x] `lib.analysis.get_dt()`
* [ ] `lib.analysis.split_dataframe_in_equal_blocks()`
* [ ] `lib.analysis.split_dataframe()`

2024-05-17 16:26 UTC, kosovan commented
@pm-blanco Are these analysis functions actually used by pyMBE? Maybe we should consider removing or at least updating some of them?

2024-05-17 16:44 UTC, pm-blanco commented
@kosovan `block_analyze` and functions called therein are currently called by the sample scripts `samples/branched_polyampholyte.py`, `samples/peptide_mixture_grxmc_ideal.py`, `samples/peptide.py`  and also by the script that we use to reproduce the data of our manuscript , `samples/Beyer2024/create_paper_data.py` , via `analysis.analyze_time_series()`. I am not sure if all functions in `lib.analysis` are actually called within pyMBE, it would definitively by worth checking if we can clean-up some. Updating them to their current counterpart in our private repository is a good idea, would you take care of that?

2024-06-05 11:48 UTC, pm-blanco commented
@kosovan I took the liberty to finish this PR. I cleaned up `lib/analysis.py` of all the functions that are not used within pyMBE and I updated the functions to work following our current standards. I have also provided unit tests for all the functions in the library, which cover the 100% of the code.

2024-06-05 15:35 UTC, pm-blanco commented
@paobtorres this PR is now ready for review

2024-06-06 17:11 UTC, paobtorres commented on lib/analysis.py
There are a few inconsistencies in the docstring. For example, in Args from `analyze_time_series()` has no items (-) and the Returns provides only the format output. Then, in `block_analyze()` each Args has an item symbol (-) the the Returns contains the variable name of the output.

2024-06-06 21:15 UTC, paobtorres requested changes
I think the docstring in `analysis.py` should be changed to keep a consisting format. Other than that, I did some testing and everything ran successfully.

2024-06-07 09:59 UTC, pm-blanco commented on lib/analysis.py
@paobtorres thank you for your revision and for bringing up this point. I have reviewed the docstrings of `analysis.py` and `pyMBE.py` to try to standardize the format and, in the process, I solved numerous inaccuracies and ambiguities on variable types. Regarding the format of the Return arguments, I think that we should actually not enforce that there should be a variable name in the docstrings because there are some functions like `pmb.check_if_df_cell_has_a_value` or `check_if_name_is_defined_in_df` that do not really store their output into a variable but simply return it and then the user can put any arbitrary variable name to it. I would suggest to either drop all variable names for return arguments (because they are actually not important for users anyway) or to only add the variable name in return arguments when it is actually defined in the function.

2024-06-07 12:07 UTC, paobtorres commented on lib/analysis.py
@pm-blanco I think that depends on which Python code docstring guideline we follow. I believe that when there is a variable name we should put it because it helps the user to better understand how each function works by reading the docstring.

2024-06-07 12:13 UTC, pm-blanco commented on lib/analysis.py
@paobtorres we follow the [Google Style Python Docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html). In that standard, the variable names is not provided for return arguments. I do not think that it is enforced that we should not provide variable names, so we can agree that we provide variable names for return variables to help users reading the code but we do not enforce that all functions should have a return variable name.

2024-06-07 14:20 UTC, paobtorres approved these changes
I reviewed the changes and quickly ran a test everything is ok.

2024-06-07 14:22 UTC, merged